### ISSUE TITLE
conflict between ruby 2.4.0 and rails 4.x

### ISSUE THREAD

**Issue by nathanallen** [SF-WDI-LABS/cookie_monster_app#5]
* downgrading to ruby 2.3.3 is one workaround
* updating this lab to rails v5 is another (#6)

**Comment by wakaspar** [comment]
Error received when running 'rails s' in Ruby 2.4.0:

```
Aang:cookie-monster-app Will$ rails s
=> Booting WEBrick
=> Rails 4.2.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
/Users/Will/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/Users/Will/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
Exiting
/Users/Will/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:125:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
	from /Users/Will/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/Will/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/Will/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/Will/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/Will/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/Will/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/Will/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /Users/Will/.rvm/gems/ruby-2.4.0/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	 ... 5540 levels...
	from /Users/Will/wdi/cookie-monster-app/bin/spring:15:in `require'
	from /Users/Will/wdi/cookie-monster-app/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```
